#!C:\Users\ivnne\OneDrive\PowerShell\Posh-Stem\stem_testing\env\Scripts\python.exe
# Copyright 2014, Damian Johnson and The Tor Project
# See LICENSE for licensing information

import stem.interpreter

if __name__ == '__main__':
  stem.interpreter.main()
